def test_many():
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"

def test_enough():
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
    assert 1 == 1, "one is one"
