"""Sort every catalogue family into what it would take zanity to detect it, as a work plan.

Heuristic and unreviewed: it reads platform and detection metadata, not the weakness itself.
Treat each bucket as a starting point for review, never as a coverage claim.

    python catalogue/triage.py        # writes catalogue/TRIAGE.md
"""

import json
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUR_LANGUAGES = {"Python", "JavaScript", "TypeScript", "Java", "Go", "Rust", "Zig"}
GENERIC = {"Not Language-Specific", "Interpreted", "Compiled", "Object-Oriented"}
HARDWARE_WORDS = ("Hardware", "System on Chip", "Verilog", "VHDL")
OTHER_LANGUAGES = {"C", "C++", "PHP", "C#", "Perl", "ASP.NET", "Memory-Unsafe", "Assembly", "Ruby", "Objective-C", "Swift", "Kotlin", "Shell"}

BUCKETS = {
    "mapped": "Has a zanity rule",
    "static": "Static analysis can find it (upstream says so); a candidate for a deterministic rule",
    "inference": "Visible in source but needs judgement; a candidate for a --infer question",
    "other-languages": "Specific to languages zanity has no grammar for yet (C, C++, PHP, C#...)",
    "hardware": "Hardware design weaknesses; not in software source",
    "abstract": "A class or pillar; covered through its more specific children",
    "deprecated": "Deprecated upstream; do not build new rules on it",
    "runtime-or-process": "Needs a running system, a specification or a person; not decidable from source",
}


def platforms(entry: dict) -> list[str]:
    assert "id" in entry, f"a catalogue entry has no id (keys: {sorted(entry)}); copy catalogue.json from the engineering-error-catalogue repository"
    listed = entry.get("applicable_platforms", [])
    names = [p.get("Name") or p.get("Class") or "" for p in listed]
    assert len(names) == len(listed), f"{entry['id']}: read {len(names)} platform names from {len(listed)} platforms; each platform needs a Name or Class"
    return names


def out_of_scope(entry: dict) -> str | None:
    """The bucket of an entry zanity won't build a rule for yet, or None if it could."""
    assert "rule_ids" in entry and "active" in entry, f"{entry.get('id')} lacks rule_ids or active; run catalogue/sync.py, which writes both"
    if entry["rule_ids"]:
        return "mapped"
    if not entry["active"]:
        return "deprecated"
    if any(word in name for name in platforms(entry) for word in HARDWARE_WORDS):
        return "hardware"
    languages = {p.get("Name") or p.get("Class") for p in entry.get("applicable_platforms", []) if p.get("kind") == "Language"}
    if languages and not languages & (OUR_LANGUAGES | GENERIC) and languages & OTHER_LANGUAGES:
        return "other-languages"
    found = "abstract" if entry.get("abstraction") in ("Pillar", "Class") else None
    assert found is None or found in BUCKETS, f"{entry['id']}: '{found}' is not a bucket in BUCKETS; add it there so it gets a row"
    return found


def detection(entry: dict) -> str:
    """How a weakness zanity could take on would be found: statically, by inference, or neither."""
    methods = {m.get("method", "") for m in entry.get("upstream_detection_methods", [])} | set(entry.get("detection_methods", []))
    assert all(isinstance(m, str) for m in methods), f"{entry['id']}: detection methods {sorted(map(repr, methods))} are not all names; copy catalogue.json from the engineering-error-catalogue repository"
    if any("Static" in m or m == "static" for m in methods):
        return "static"
    if methods & {"specification", "runtime", "manual", "configuration"}:
        return "runtime-or-process"
    found = "inference" if entry.get("abstraction") in ("Base", "Variant", "Compound") else "runtime-or-process"
    assert found in BUCKETS, f"{entry['id']}: '{found}' is not a bucket in BUCKETS; add it there so it gets a row"
    return found


def bucket(entry: dict) -> str:
    found = out_of_scope(entry) or detection(entry)
    assert found in BUCKETS, f"{entry['id']} landed in '{found}', which BUCKETS doesn't list; add it there so it gets a row"
    assert found != "mapped" or entry["rule_ids"], f"{entry['id']} counts as mapped with no rule_ids; run catalogue/sync.py"
    return found


def write_triage() -> None:
    catalogue = json.loads((HERE / "catalogue.json").read_text())
    assert catalogue["entries"], "catalogue/catalogue.json has no entries; copy catalogue.json from the engineering-error-catalogue repository"
    groups: dict[str, list[dict]] = defaultdict(list)
    for entry in catalogue["entries"]:
        groups[bucket(entry)].append(entry)
    counts = Counter({k: len(v) for k, v in groups.items()})
    assert sum(counts.values()) == len(catalogue["entries"]), f"bucketed {sum(counts.values())} of {len(catalogue['entries'])} entries; bucket() must place each entry exactly once"
    lines = [
        "# What it would take zanity to detect each catalogue family",
        "",
        "Generated by `python catalogue/triage.py` from platform and detection metadata. Heuristic and",
        "unreviewed: a bucket is a starting point for review, not a claim about the weakness.",
        "",
        "| Bucket | Families | Meaning |",
        "|---|---:|---|",
    ]
    for name, meaning in BUCKETS.items():
        lines.append(f"| {name} | {counts[name]} | {meaning} |")
    lines += ["", f"Total: {sum(counts.values())} families.", ""]
    for name in ("static", "inference"):
        lines += [f"## {name}: next candidates", "", "| ID | Kind | Title |", "|---|---|---|"]
        ranked = sorted(groups[name], key=lambda e: (e["assessment_kind"] != "defect", e.get("abstraction") != "Base", e["id"]))
        lines += [f"| {e['id']} | {e['assessment_kind']} | {e['title']} |" for e in ranked]
        lines.append("")
    (HERE / "TRIAGE.md").write_text("\n".join(lines))
    for name in BUCKETS:
        print(f"{name:20} {counts[name]}")


if __name__ == "__main__":
    write_triage()
